<?php
$z[0]=Array("channel","\n       <li><a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a></li>\n        <!--<li><a href=\"#\" target=\"_blank\">祛斑美肤</a></li>\n        <li><a href=\"#\" target=\"_blank\">零感脱毛</a></li>\n        <li><a href=\"#\" target=\"_blank\">祛痘除疤</a></li>\n        <li><a href=\"#\" target=\"_blank\">嫩肤美白</a></li>\n        <li><a href=\"#\" target=\"_blank\">紧肤除皱</a></li> -->\n        ",12,475);
$z[0][4]['type']="son";
$z[0][4]['noself']="true";

?>