<ul>
          <li class="li01">
            <p><a href="http://wt.zoosnet.net/LR/Chatpre.aspx?id=LRW41861572&r=shouji&p=shouji" target="_blank"><img src="[field:picname/]"  width="70" height="85"/></a></p>
          </li>
          <li class="li02">
            <h3>[field:title/]   [field:zhiwei/]</h3>
            <h4>擅长项目: [field:shanchang function="cn_substr(@me,85)"/]... <a href="[field:arcurl/]" target="_blank">[详情]</a></h4>
            <h2><a href="http://wt.zoosnet.net/LR/Chatpre.aspx?id=LRW41861572&r=shouji&p=shouji" target="_blank"><img src="/templets/shouji/images/dhyy.png" width="61" height="16"/></a> <a href="http://wt.zoosnet.net/LR/Chatpre.aspx?id=LRW41861572&r=shouji&p=shouji" target="_blank"><img src="/templets/shouji/images/zxzx.png" width="61" height="16"/></a></h2>
          </li>
        </ul>