<ul>
          <li class="li01">
            <p><img src="/templets/shouji/images/dh04_2_1.png" width="70" height="85"/></p>
          </li>
          <li class="li02">
            <h3>[field:title/] &nbsp; [field:zhiwei/]</h3>
            <h4>擅长项目: [field:shanchang function="cn_substr(@me,85)"/]... <a href="[field:arcurl/]" target="_blank">[详情]</a></h4>
            <h2><a href="http://wt.zoosnet.net/LR/Chatpre.aspx?id=LRW41861572" target="_blank"><img src="/templets/shouji/images/dhyy.png" width="49" height="11"/></a>&nbsp;<a href="http://wt.zoosnet.net/LR/Chatpre.aspx?id=LRW41861572" target="_blank"><img src="/templets/shouji/images/zxzx.png" width="49" height="11"/></a></h2>
          </li>
        </ul>