<ul>
       {dede:channel type='son' noself='true' typeid='2'}
       <li><a href="[field:typelink/]" target="_blank">[field:typename/]</a></li>
        <!--<li><a href="#" target="_blank">祛斑美肤</a></li>
        <li><a href="#" target="_blank">零感脱毛</a></li>
        <li><a href="#" target="_blank">祛痘除疤</a></li>
        <li><a href="#" target="_blank">嫩肤美白</a></li>
        <li><a href="#" target="_blank">紧肤除皱</a></li> -->
        {/dede:channel}
      </ul>