<?php
$z[0]=Array("global","",176,201);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",267,292);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",354,379);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",412,438);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",566,593);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",666,693);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",696,722);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",875,902);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",914,946);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",993,1019);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1072,1107);
$z[10][4]['name']="innerTopBanner1";
$z[11]=Array("myad","",1141,1176);
$z[11][4]['name']="innerTopBanner2";
$z[12]=Array("global","",1470,1495);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n      	",1534,1775);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",1863,1888);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\n          ",2681,2809);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>