<?php
$z[0]=Array("field","",250,273);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",390,420);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",456,483);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("channel","\n        <li><a href='[field:typelink/]' target=\"_blank\">[field:typename/]</a></li>\n        ",1152,1292);
$z[4][4]['type']="top";
$z[4][4]['row']="6";
$z[5]=Array("list","\n      <ul>\n        <li><h3><a href=\"[field:typelink/]\" target=\"_blank\">[field:title function=\"cn_substr(@me,16)\"/]</a></h3></li>\n        <li><p>[field:description function=\"cn_substr(@me,68)\"/]...<a href=\"[field:typelink/]\" target=\"_blank\">[详细]</a></p></li>\n      </ul>\n      ",1524,1841);
$z[5][4]['pagesize']="6";
$z[6]=Array("global","",1954,1976);
$z[6][4]['name']="address";
$z[7]=Array("global","",1997,2015);
$z[7][4]['name']="tel";

?>