<?php
$z[0]=Array("field","",254,277);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",278,304);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",478,508);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",545,572);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",761,795);
$z[4][4]['filename']="tel.htm";
$z[5]=Array("channel","\r\n        <li><a href='[field:typelink/]' target=\"_blank\">[field:typename/]</a></li>\r\n        ",1435,1577);
$z[5][4]['type']="top";
$z[5][4]['row']="6";
$z[6]=Array("list","\r\n        <ul>\r\n          <li class=\"li01\">\r\n            <p><img src=\"[field:picname/]\"  width=\"70\" height=\"85\"/></p>\r\n          </li>\r\n          <li class=\"li02\">\r\n            <h3>[field:title/]   [field:zhiwei/]</h3>\r\n            <h4>擅长项目: [field:shanchang function=\"cn_substr(@me,85)\"/]... <a href=\"[field:arcurl/]\" target=\"_blank\">[详情]</a></h4>\r\n            <h2><a href=\"javascript:void(0)\" onclick=\"LR_HideInvite();openZoosUrl('chatwin','&e=wap');return false;\" target=\"_blank\"><img src=\"/templets/shouji/images/dhyy.png\" width=\"61\" height=\"16\"/></a><a href=\"javascript:void(0)\" onclick=\"LR_HideInvite();openZoosUrl('chatwin','&e=wap');return false;\" target=\"_blank\"><img src=\"/templets/shouji/images/zxzx.png\" width=\"61\" height=\"16\"/></a></h2>\r\n          </li>\r\n        </ul>\r\n        ",1988,2891);
$z[6][4]['addfields']="zhiwei,shanchang";
$z[6][4]['orderby']="hot";
$z[6][4]['row']="6";
$z[6][4]['channelid']="1";
$z[6][4]['typeid']="5";
$z[7]=Array("global","",4068,4090);
$z[7][4]['name']="address";
$z[8]=Array("global","",4112,4130);
$z[8][4]['name']="tel";

?>