<?php
$z[0]=Array("field","",262,285);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",286,312);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",490,520);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",559,586);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",783,817);
$z[4][4]['filename']="tel.htm";
$z[5]=Array("channel","\r\n\r\n        <li><a href='[field:typelink/]' target=\"_blank\">[field:typename/]</a></li>\r\n\r\n        ",1477,1623);
$z[5][4]['type']="top";
$z[5][4]['row']="6";
$z[6]=Array("field","",2259,2277);
$z[6][4]['name']="body";

?>