<?php
$z[0]=Array("field","",254,277);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",278,304);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",478,508);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",545,572);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",761,795);
$z[4][4]['filename']="tel.htm";
$z[5]=Array("channel","\r\n        <li><a href='[field:typelink/]' target=\"_blank\">[field:typename/]</a></li>\r\n        ",1436,1578);
$z[5][4]['type']="top";
$z[5][4]['row']="6";
$z[6]=Array("include","",1854,1895);
$z[6][4]['filename']="shouji/hdp.htm";
$z[7]=Array("channel","\r\n       <li><a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a></li>\r\n        ",1952,2096);
$z[7][4]['type']="son";
$z[7][4]['typeid']="3";
$z[8]=Array("global","",2228,2250);
$z[8][4]['name']="address";
$z[9]=Array("global","",2272,2290);
$z[9][4]['name']="tel";

?>